version: '3.3'

services:
  app:
  backend:
    build: ./backend
    ports:
      -  "8080:8080"
    env_file:
      - backend/.env
    depends_on:
      - postgres
    restart: unless-stopped
  postgres:
    container_name: postgresql
    image: postgres:12.2

    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'wizard'
    ports:
      - 5432:5432
    restart: unless-stopped
