package dbRepo

import (
	"github.com/jmoiron/sqlx"
	_ "github.com/lib/pq"
	"todomodule/app"
	"todomodule/domain"
)

var schema = `CREATE TABLE if not exists todos (
id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
todo  text NOT NULL
)`

type dbRepo struct {
	db *sqlx.DB
}

func (r dbRepo) Create(todo domain.Todo) error {
	// TODO Добавить on conflict
	_, err := r.db.Exec(`INSERT INTO todos (todo) VALUES ($1)`, todo.Name)
	return err
}
func (r dbRepo) GetAll() ([]domain.Todo, error) {
	var todos []Todo
	err := r.db.Select(&todos, "select * from todos")

	domainTodos := make([]domain.Todo, 0, len(todos))
	for i := range todos {
		domainTodos = append(domainTodos, domain.Todo{Name: todos[i].Name})
	}
	return domainTodos, err
}

func NewDbRepo(db *sqlx.DB) (app.Repo, error) {
	_, err := db.Exec(schema)
	return &dbRepo{db: db}, err
}
